import type { Flatfile } from '@flatfile/api'

export const documents: Flatfile.DocumentConfig[] = [
  {
    title: 'Welcome',
    body: "# Welcome to your Real Estate Workbook!\n\n## This workbook is designed to help you manage your real estate business data.\n\nInside, you'll find sheets for managing:\n\n- **Properties:** Maintain your property listings with details such as address, price, features, status, and more.\n- **Property Types:** Categorize properties into different types like residential, commercial, multifamily, etc.\n- **Agents:** Keep track of your real estate agents, including their contact information, license numbers, and specializations.\n- **Clients:** Manage your client database, including buyers, sellers, renters, and landlords.\n- **Transactions:** Record all property transactions, including sales, rentals, and leases.\n\n## Getting Started:\n\n1. **Explore the Sheets:** Familiarize yourself with the different sheets and their columns.\n2. **Import Your Data:** Use Flatfile's import capabilities to populate the sheets with your existing real estate data. Sample files are provided for each sheet.\n3. **Manage and Validate:** Leverage the built-in data validation and transformation features to ensure your data is accurate and consistent.\n\nHappy Flatfiling!",
  },
  {
    title: 'Property Management Guide',
    body: '# Property Management Guide\n\n## Best Practices for Managing Properties in the Workbook\n\n### Adding New Properties\n\n1. **Ensure Unique IDs:** Each property must have a unique Property ID starting with \'PROP\'. Example: PROP001, PROP002, etc.\n2. **Complete Required Fields:** At minimum, fill in all required fields including address, city, state, zip code, country, and price.\n3. **Assign Property Types:** Always associate properties with a Property Type from the Property Types sheet.\n4. **Update Status Regularly:** Keep the property status current - available, pending, sold, off_market, or rented.\n\n### Managing Property Types\n\n1. **Use Descriptive Names:** Create clear, specific names for property types (e.g., "Single-Family Home", "Commercial Office").\n2. **Add Descriptions:** Include detailed descriptions to help users understand each property type.\n\n### Images and Virtual Tours\n\n1. **Use High-Quality Images:** Provide clear, professional images of properties via URLs.\n2. **Include Virtual Tours:** When available, add links to virtual tours to enhance property listings.\n\n### Property Features\n\n1. **Be Specific:** List specific features that make the property unique.\n2. **Include Amenities:** Mention amenities like pools, garages, updated kitchens, etc.\n\n### Regular Maintenance\n\n1. **Update Statuses:** Regularly review and update property statuses.\n2. **Verify Prices:** Ensure listing prices are current and accurate.\n3. **Check Agent Assignments:** Confirm properties are assigned to the correct listing agents.',
  },
  {
    title: 'Transaction Processing',
    body: "# Transaction Processing Guide\n\n## How to Record and Track Real Estate Transactions\n\n### Creating New Transactions\n\n1. **Generate Transaction IDs:** Each transaction must have a unique Transaction ID starting with 'TRX'. Example: TRX001, TRX002, etc.\n2. **Link Related Entities:** Always link transactions to the relevant Property, Client, and Agent records.\n3. **Select Transaction Type:** Specify whether the transaction is a sale, rental, or lease.\n4. **Record Dates Properly:** Use YYYY-MM-DD format for all dates (transaction date, closing date).\n\n### Transaction Statuses\n\n1. **Update Status Regularly:** Keep the transaction status updated as it progresses:\n   - Pending: Initial stage of the transaction\n   - Under Contract: When a contract has been signed\n   - Closed: When the transaction is complete\n   - Cancelled: If the transaction is terminated\n\n### Financial Details\n\n1. **Record Accurate Prices:** Enter the exact sale prices or rental/lease amounts.\n2. **Calculate Commissions:** Enter the correct commission amounts for agents.\n3. **Maintain Documentation:** Use the notes field to reference relevant documents or special terms.\n\n### Best Practices\n\n1. **Regular Updates:** Update transaction statuses weekly or as changes occur.\n2. **Verify Client & Agent Info:** Ensure all linked client and agent information is current.\n3. **Cross-Check Property Status:** Make sure the property status is updated when a transaction changes status.\n4. **Keep Notes Detailed:** Add specific notes about unique circumstances or requirements for each transaction.",
  },
  {
    title: 'Client Management',
    body: "# Client Management Guide\n\n## Effectively Managing Client Records\n\n### Adding New Clients\n\n1. **Create Unique Client IDs:** Each client must have a unique Client ID starting with 'CLT'. Example: CLT001, CLT002, etc.\n2. **Collect Complete Information:** Gather comprehensive contact details, including email, phone, and address.\n3. **Specify Client Type:** Indicate whether the client is a buyer, seller, renter, landlord, or both.\n4. **Assign Primary Agent:** Link each client to their primary real estate agent.\n\n### Client Communications\n\n1. **Document Interactions:** Use the notes field to document important client interactions and preferences.\n2. **Track Registration Dates:** Record when clients first registered with your agency.\n3. **Maintain Privacy:** Ensure client data is protected and handled according to privacy regulations.\n\n### Updating Client Information\n\n1. **Regular Reviews:** Schedule periodic reviews of client information to ensure it remains current.\n2. **Update Client Types:** As client needs change (e.g., from buyer to seller), update their client type accordingly.\n3. **Verify Contact Details:** Regularly confirm that phone numbers and email addresses are still valid.\n\n### Managing Client Relationships\n\n1. **Note Preferences:** Document client preferences regarding property types, locations, price ranges, etc.\n2. **Track Property Viewings:** Keep records of which properties clients have viewed and their feedback.\n3. **Monitor Transaction History:** For repeat clients, maintain a history of previous transactions.\n\n### Best Practices\n\n1. **Consistent Format:** Use consistent formatting for phone numbers, addresses, and other contact details.\n2. **Complete Records:** Aim for 100% completion of client profiles, even for non-required fields.\n3. **Regular Cleanups:** Periodically review and clean up inactive client records.",
  },
]
